services:
  mailing_service:
    restart: always
    image: ghcr.io/kryseyt/mailing_service:${IMAGE_VERSION}
    environment:
      - BACKENDTASK1_POSTGRESQL_URL=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  db:
    driver: local
