"""empty message

Revision ID: 6b3da51d6ebf
Revises: 
Create Date: 2023-01-05 01:21:21.875588

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6b3da51d6ebf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailing_mobile_operator_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_mailing_mobile_operator_codes_id'), 'mailing_mobile_operator_codes', ['id'], unique=False)
    op.create_table('mailing_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_index(op.f('ix_mailing_tags_id'), 'mailing_tags', ['id'], unique=False)
    op.create_table('mailings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailings_id'), 'mailings', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('delivered', 'not_delivered', name='messagestatus'), nullable=True),
    sa.Column('mailing_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.Column('phone_operator_code', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['mailing_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('mailings_and_mailing_tags_table',
    sa.Column('mailing_id', sa.Integer(), nullable=True),
    sa.Column('mailing_tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mailing_id'], ['mailings.id'], ),
    sa.ForeignKeyConstraint(['mailing_tag_id'], ['mailing_tags.id'], )
    )
    op.create_table('mailings_and_operator_codes_table',
    sa.Column('mailing_id', sa.Integer(), nullable=True),
    sa.Column('mailing_mobile_operator_codes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mailing_id'], ['mailings.id'], ),
    sa.ForeignKeyConstraint(['mailing_mobile_operator_codes_id'], ['mailing_mobile_operator_codes.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailings_and_operator_codes_table')
    op.drop_table('mailings_and_mailing_tags_table')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_mailings_id'), table_name='mailings')
    op.drop_table('mailings')
    op.drop_index(op.f('ix_mailing_tags_id'), table_name='mailing_tags')
    op.drop_table('mailing_tags')
    op.drop_index(op.f('ix_mailing_mobile_operator_codes_id'), table_name='mailing_mobile_operator_codes')
    op.drop_table('mailing_mobile_operator_codes')
    # ### end Alembic commands ###
