name: Mypy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@v1
    
    - name: Build Docker image
      run: docker build . -t img

    - name: Run mypy
      run: docker run img mypy src/ --strict
