name: PythonCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: |
        pip install mypy
        pip install -r requirements.txt
    - name: mypy
      run: |
        mypy app --strict
    - name: pytest
      run: |
        pytest tests/
