name: Tests
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.11'
    steps:
    - uses: actions/checkout@master

    - name: Build Docker image
      run: docker compose -f docker-compose.yml -f tests.yml build

    - name: Run tests
      run: docker compose -f docker-compose.yml -f tests.yml up --abort-on-container-exit
      
    - name: Copy coverage data from container
      run: docker compose cp mailing_service:/mailing_service/coverage.xml ./

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        directory: ./
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml
        flags: unit-tests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
